### ISSUE TITLE
Scripture not loading in catechism for young children

### ISSUE THREAD

**Issue by Typingkid** [steveszc/catechesis#38]
I went to catechesis website, and went to the catechism for young children. Then I went to the first question and there was an error loading the scripture.

**Comment by steveszc** [comment]
Thanks for filing this issue. It looks like this is happening because Catechism For Young Children has no proof texts, but the app is still trying to load proof text verses from the ESV api. Since there are no proof texts there is no query provided to the ESV API, so the api responds with an error because it requires a query (`q` query param). 

This can be fixed by early returning from the scripture route's model hook when there are no proofs, before we try to load the verses from the ESV API.

This would be a fairly straight forward fix if you are interested in contributing.

**Comment by steveszc** [comment]
We already early return here https://github.com/steveszc/catechesis/blob/main/app/routes/catechism/question/scripture.ts#L69

So you could add an additional condition here, so that we early return `if` we're in fastboot `or` if there are no proofs (you could check the length of the proofs array to see if it is 0).

**Comment by steveszc** [comment]
If you'd like help opening your first PR to contribute this fix I would be happy to pair with you on it. @Typingkid

**Comment by Typingkid** [comment]
Ya no problem, I went on and made the fix so hopefully it works!

**Comment by Typingkid** [comment]
It Worked!
